import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
import dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

async function main() {
  console.log('Start seeding...');

  // Create admin user
  const hashedPassword = await bcrypt.hash('admin123', 10);
  
  const admin = await prisma.user.upsert({
    where: { username: 'admin' },
    update: {},
    create: {
      username: 'admin',
      email: 'admin@cloudsentry.local',
      password: hashedPassword,
      role: 'admin',
    },
  });

  console.log('Created admin user:', admin);

  // Create sample syslog channels
  const sampleChannels = [
    {
      name: '防火墙服务器',
      sourceIdentifier: '192.168.1.1',
      description: '主防火墙设备，用于监控网络边界安全事件',
      enabled: true,
      eventCount: 1250,
      lastEventAt: new Date('2024-01-12T10:30:00'),
    },
    {
      name: 'Web服务器集群',
      sourceIdentifier: '192.168.1.10',
      description: 'Web应用服务器集群，监控HTTP/HTTPS流量',
      enabled: true,
      eventCount: 3420,
      lastEventAt: new Date('2024-01-12T11:45:00'),
    },
    {
      name: '数据库服务器',
      sourceIdentifier: '192.168.1.20',
      description: 'PostgreSQL数据库服务器，监控数据库访问日志',
      enabled: true,
      eventCount: 890,
      lastEventAt: new Date('2024-01-12T09:15:00'),
    },
    {
      name: 'VPN网关',
      sourceIdentifier: '10.0.0.1',
      description: 'VPN接入网关，监控远程访问连接',
      enabled: true,
      eventCount: 567,
      lastEventAt: new Date('2024-01-12T08:20:00'),
    },
    {
      name: '入侵检测系统',
      sourceIdentifier: '192.168.1.50',
      description: 'IDS/IPS设备，实时检测网络入侵行为',
      enabled: true,
      eventCount: 2100,
      lastEventAt: new Date('2024-01-12T11:55:00'),
    },
    {
      name: '邮件服务器',
      sourceIdentifier: '192.168.1.30',
      description: '企业邮件服务器，监控邮件安全事件',
      enabled: false,
      eventCount: 456,
      lastEventAt: new Date('2024-01-10T16:30:00'),
    },
    {
      name: 'DNS服务器',
      sourceIdentifier: '192.168.1.5',
      description: '内部DNS服务器，监控DNS查询日志',
      enabled: true,
      eventCount: 7800,
      lastEventAt: new Date('2024-01-12T11:58:00'),
    },
    {
      name: '堡垒机',
      sourceIdentifier: '10.0.0.10',
      description: '运维堡垒机，记录所有运维操作日志',
      enabled: true,
      eventCount: 234,
      lastEventAt: new Date('2024-01-12T10:00:00'),
    },
  ];

  const createdChannels: { id: string; sourceIdentifier: string }[] = [];
  for (const channelData of sampleChannels) {
    const channel = await prisma.syslogChannel.upsert({
      where: { sourceIdentifier: channelData.sourceIdentifier },
      update: {},
      create: channelData,
    });
    createdChannels.push({ id: channel.id, sourceIdentifier: channel.sourceIdentifier });
  }

  console.log('Created sample syslog channels');

  // Create sample security events with channel associations
  const sampleEvents = [
    {
      severity: 'critical',
      category: 'intrusion',
      attackType: 'brute_force',
      source: '192.168.1.100',
      sourceIp: '192.168.1.100',
      destination: '192.168.1.200',
      destinationIp: '192.168.1.200',
      message: 'Brute force attack detected on SSH service',
      rawLog: 'Failed password for invalid user admin from 192.168.1.100 port 56789 ssh2',
      rawData: 'Failed password for invalid user admin from 192.168.1.100 port 56789 ssh2',
      protocol: 'TCP',
      port: 22,
      destinationPort: 22,
      tags: ['ssh', 'brute-force', 'authentication'],
      threatName: 'SSH暴力破解攻击',
      threatLevel: 'critical',
      sourceChannel: '入侵检测系统',
      country: '中国',
      city: '北京',
      region: '华北',
      deviceType: 'ids',
      action: 'block',
    },
    {
      severity: 'high',
      category: 'malware',
      attackType: 'trojan',
      source: '192.168.1.105',
      sourceIp: '192.168.1.105',
      message: 'Malware detected: Trojan.Generic.12345',
      rawLog: 'AV Alert: Trojan.Generic.12345 found in /tmp/suspicious.exe',
      rawData: 'AV Alert: Trojan.Generic.12345 found in /tmp/suspicious.exe',
      tags: ['malware', 'trojan'],
      threatName: '木马病毒检测',
      threatLevel: 'high',
      sourceChannel: 'Web服务器集群',
      country: '中国',
      city: '上海',
      region: '华东',
      deviceType: 'endpoint',
      action: 'quarantine',
    },
    {
      severity: 'medium',
      category: 'policy_violation',
      attackType: 'unauthorized_access',
      source: '10.0.0.50',
      sourceIp: '10.0.0.50',
      message: 'Unauthorized access attempt to restricted resource',
      rawLog: 'HTTP 403 Forbidden - User attempted to access /admin/sensitive-data',
      rawData: 'HTTP 403 Forbidden - User attempted to access /admin/sensitive-data',
      protocol: 'HTTP',
      port: 80,
      destinationPort: 80,
      tags: ['access-control', 'policy'],
      threatName: '未授权访问尝试',
      threatLevel: 'medium',
      sourceChannel: 'Web服务器集群',
      country: '中国',
      city: '深圳',
      region: '华南',
      userName: 'john.doe',
      deviceType: 'server',
      action: 'deny',
    },
    {
      severity: 'low',
      category: 'network',
      attackType: 'dns_tunneling',
      source: '172.16.0.25',
      sourceIp: '172.16.0.25',
      destination: '8.8.8.8',
      destinationIp: '8.8.8.8',
      message: 'Unusual outbound DNS query pattern',
      rawLog: 'DNS query to suspicious domain: evil-tracker.com',
      rawData: 'DNS query to suspicious domain: evil-tracker.com',
      protocol: 'UDP',
      port: 53,
      destinationPort: 53,
      tags: ['dns', 'network'],
      threatName: '可疑DNS查询',
      threatLevel: 'low',
      sourceChannel: 'DNS服务器',
      country: '美国',
      city: '洛杉矶',
      region: '北美',
      isp: 'Google LLC',
      deviceType: 'dns',
      action: 'alert',
    },
    {
      severity: 'info',
      category: 'system',
      source: 'localhost',
      sourceIp: '127.0.0.1',
      message: 'System backup completed successfully',
      rawLog: 'Backup job completed at 2024-01-12 02:00:00',
      rawData: 'Backup job completed at 2024-01-12 02:00:00',
      tags: ['backup', 'system'],
      threatName: '系统备份完成',
      threatLevel: 'info',
      sourceChannel: '数据库服务器',
      country: '中国',
      city: '杭州',
      region: '华东',
      deviceType: 'server',
      action: 'log',
    },
    // Additional threat alerts
    {
      severity: 'critical',
      category: 'intrusion',
      attackType: 'sql_injection',
      source: '203.0.113.45',
      sourceIp: '203.0.113.45',
      destination: '192.168.1.1',
      destinationIp: '192.168.1.1',
      message: 'SQL注入攻击尝试 - 检测到恶意SQL语句',
      rawLog: 'WAF Block: SQL injection attempt detected in parameter "id": SELECT * FROM users WHERE id=1 OR 1=1--',
      rawData: 'WAF Block: SQL injection attempt detected in parameter "id": SELECT * FROM users WHERE id=1 OR 1=1--',
      protocol: 'TCP',
      port: 443,
      destinationPort: 443,
      tags: ['sql-injection', 'waf', 'web-attack'],
      threatName: 'SQL注入攻击',
      threatLevel: 'critical',
      sourceChannel: '防火墙服务器',
      country: '俄罗斯',
      city: '莫斯科',
      region: '东欧',
      isp: 'Unknown ISP',
      deviceType: 'waf',
      action: 'block',
    },
    {
      severity: 'high',
      category: 'intrusion',
      attackType: 'xss',
      source: '198.51.100.77',
      sourceIp: '198.51.100.77',
      destination: '192.168.1.10',
      destinationIp: '192.168.1.10',
      message: 'XSS跨站脚本攻击检测',
      rawLog: 'WAF Alert: XSS attempt in request body: <script>alert(document.cookie)</script>',
      rawData: 'WAF Alert: XSS attempt in request body: <script>alert(document.cookie)</script>',
      protocol: 'TCP',
      port: 80,
      destinationPort: 80,
      tags: ['xss', 'web-attack', 'script-injection'],
      threatName: 'XSS跨站脚本攻击',
      threatLevel: 'high',
      sourceChannel: 'Web服务器集群',
      country: '德国',
      city: '柏林',
      region: '西欧',
      deviceType: 'waf',
      action: 'block',
    },
    {
      severity: 'high',
      category: 'malware',
      attackType: 'ransomware',
      source: '192.168.1.88',
      sourceIp: '192.168.1.88',
      destination: '185.234.219.47',
      destinationIp: '185.234.219.47',
      message: '检测到勒索软件通信 - C&C服务器连接',
      rawLog: 'C2 Communication: Ransomware beacon detected to known malicious IP 185.234.219.47',
      rawData: 'C2 Communication: Ransomware beacon detected to known malicious IP 185.234.219.47',
      protocol: 'TCP',
      port: 8443,
      destinationPort: 8443,
      tags: ['ransomware', 'c2', 'malware'],
      threatName: '勒索软件C&C通信',
      threatLevel: 'high',
      sourceChannel: '入侵检测系统',
      country: '荷兰',
      city: '阿姆斯特丹',
      region: '西欧',
      isp: 'Malicious Hosting',
      deviceType: 'ids',
      action: 'block',
    },
    {
      severity: 'critical',
      category: 'intrusion',
      attackType: 'data_exfiltration',
      source: '192.168.1.200',
      sourceIp: '192.168.1.200',
      destination: '192.168.1.20',
      destinationIp: '192.168.1.20',
      message: '数据库异常访问 - 大量数据导出尝试',
      rawLog: 'DB Alert: Unusual data export detected - 50000 rows selected from users table in single query',
      rawData: 'DB Alert: Unusual data export detected - 50000 rows selected from users table in single query',
      protocol: 'TCP',
      port: 5432,
      destinationPort: 5432,
      tags: ['data-exfiltration', 'database', 'insider-threat'],
      threatName: '数据泄露风险',
      threatLevel: 'critical',
      sourceChannel: '数据库服务器',
      country: '中国',
      city: '广州',
      region: '华南',
      userName: 'db_admin',
      deviceType: 'database',
      action: 'alert',
    },
    {
      severity: 'medium',
      category: 'network',
      attackType: 'port_scan',
      source: '192.168.1.150',
      sourceIp: '192.168.1.150',
      destination: '91.234.99.100',
      destinationIp: '91.234.99.100',
      message: '检测到可疑的端口扫描活动',
      rawLog: 'Port Scan: Host 192.168.1.150 scanning multiple ports on external IP 91.234.99.100',
      rawData: 'Port Scan: Host 192.168.1.150 scanning multiple ports on external IP 91.234.99.100',
      protocol: 'TCP',
      port: 0,
      destinationPort: 0,
      tags: ['port-scan', 'reconnaissance', 'network'],
      threatName: '端口扫描活动',
      threatLevel: 'medium',
      sourceChannel: '防火墙服务器',
      country: '中国',
      city: '成都',
      region: '西南',
      deviceType: 'firewall',
      action: 'alert',
    },
    {
      severity: 'high',
      category: 'authentication',
      attackType: 'credential_stuffing',
      source: '10.0.0.55',
      sourceIp: '10.0.0.55',
      destination: '192.168.1.20',
      destinationIp: '192.168.1.20',
      message: 'VPN账号异地登录告警 - 短时间内多地登录',
      rawLog: 'VPN Alert: User "admin" logged in from Beijing, China and New York, USA within 5 minutes',
      rawData: 'VPN Alert: User "admin" logged in from Beijing, China and New York, USA within 5 minutes',
      protocol: 'UDP',
      port: 1194,
      destinationPort: 1194,
      tags: ['vpn', 'impossible-travel', 'authentication'],
      threatName: 'VPN异常登录',
      threatLevel: 'high',
      sourceChannel: 'VPN网关',
      country: '美国',
      city: '纽约',
      region: '北美',
      userName: 'admin',
      deviceType: 'vpn',
      action: 'alert',
    },
    {
      severity: 'medium',
      category: 'policy_violation',
      attackType: 'privilege_escalation',
      source: '192.168.1.75',
      sourceIp: '192.168.1.75',
      message: '敏感文件访问告警 - 超出权限范围',
      rawLog: 'File Access: User "john.doe" attempted to access /sensitive/financial-reports/ without proper clearance',
      rawData: 'File Access: User "john.doe" attempted to access /sensitive/financial-reports/ without proper clearance',
      tags: ['file-access', 'policy-violation', 'privilege-escalation'],
      threatName: '越权文件访问',
      threatLevel: 'medium',
      sourceChannel: '堡垒机',
      country: '中国',
      city: '武汉',
      region: '华中',
      userName: 'john.doe',
      deviceType: 'bastion',
      action: 'deny',
    },
    {
      severity: 'low',
      category: 'network',
      attackType: 'arp_spoofing',
      source: '192.168.1.180',
      sourceIp: '192.168.1.180',
      destination: '224.0.0.1',
      destinationIp: '224.0.0.1',
      message: '异常ARP请求检测 - 可能存在ARP欺骗',
      rawLog: 'ARP Alert: Abnormal ARP requests from 192.168.1.180, possible ARP spoofing attempt',
      rawData: 'ARP Alert: Abnormal ARP requests from 192.168.1.180, possible ARP spoofing attempt',
      protocol: 'ARP',
      tags: ['arp-spoofing', 'network', 'man-in-the-middle'],
      threatName: 'ARP欺骗尝试',
      threatLevel: 'low',
      sourceChannel: '入侵检测系统',
      country: '中国',
      city: '南京',
      region: '华东',
      deviceType: 'ids',
      action: 'alert',
    },
    {
      severity: 'info',
      category: 'system',
      source: '192.168.1.10',
      sourceIp: '192.168.1.10',
      message: '系统补丁更新完成 - 安全更新已应用',
      rawLog: 'Patch Update: Security patches KB5034441, KB5034467 installed successfully',
      rawData: 'Patch Update: Security patches KB5034441, KB5034467 installed successfully',
      tags: ['patch', 'system', 'update'],
      threatName: '安全补丁更新',
      threatLevel: 'info',
      sourceChannel: 'Web服务器集群',
      country: '中国',
      city: '西安',
      region: '西北',
      deviceType: 'server',
      action: 'log',
    },
    {
      severity: 'critical',
      category: 'malware',
      attackType: 'cryptominer',
      source: '192.168.1.95',
      sourceIp: '192.168.1.95',
      message: '检测到挖矿程序运行',
      rawLog: 'Crypto Miner: XMRig process detected running on host 192.168.1.95 with high CPU usage',
      rawData: 'Crypto Miner: XMRig process detected running on host 192.168.1.95 with high CPU usage',
      tags: ['cryptominer', 'malware', 'resource-abuse'],
      threatName: '挖矿程序检测',
      threatLevel: 'critical',
      sourceChannel: '入侵检测系统',
      country: '中国',
      city: '重庆',
      region: '西南',
      deviceType: 'endpoint',
      action: 'terminate',
    },
    {
      severity: 'high',
      category: 'intrusion',
      attackType: 'phishing',
      source: '45.33.32.156',
      sourceIp: '45.33.32.156',
      destination: '192.168.1.30',
      destinationIp: '192.168.1.30',
      message: '邮件钓鱼攻击检测 - 恶意附件拦截',
      rawLog: 'Email Security: Phishing email with malicious attachment blocked from sender spoofed@legit-company.com',
      rawData: 'Email Security: Phishing email with malicious attachment blocked from sender spoofed@legit-company.com',
      protocol: 'SMTP',
      port: 25,
      destinationPort: 25,
      tags: ['phishing', 'email', 'social-engineering'],
      threatName: '钓鱼邮件攻击',
      threatLevel: 'high',
      sourceChannel: '邮件服务器',
      country: '尼日利亚',
      city: '拉各斯',
      region: '非洲',
      deviceType: 'email',
      action: 'block',
    },
    {
      severity: 'medium',
      category: 'authentication',
      attackType: 'password_policy',
      source: '192.168.1.200',
      sourceIp: '192.168.1.200',
      message: '特权账户密码过期提醒',
      rawLog: 'Password Policy: Privileged account "svc_backup" password expires in 7 days',
      rawData: 'Password Policy: Privileged account "svc_backup" password expires in 7 days',
      tags: ['password', 'policy', 'privileged-account'],
      threatName: '密码过期提醒',
      threatLevel: 'medium',
      sourceChannel: '堡垒机',
      country: '中国',
      city: '天津',
      region: '华北',
      userName: 'svc_backup',
      deviceType: 'bastion',
      action: 'alert',
    },
    {
      severity: 'low',
      category: 'network',
      attackType: 'traffic_anomaly',
      source: '192.168.1.5',
      sourceIp: '192.168.1.5',
      destination: '192.168.1.255',
      destinationIp: '192.168.1.255',
      message: '网络广播流量异常增加',
      rawLog: 'Network: Broadcast traffic from 192.168.1.5 increased by 300% in last hour',
      rawData: 'Network: Broadcast traffic from 192.168.1.5 increased by 300% in last hour',
      protocol: 'UDP',
      tags: ['broadcast', 'network', 'traffic-anomaly'],
      threatName: '广播流量异常',
      threatLevel: 'low',
      sourceChannel: 'DNS服务器',
      country: '中国',
      city: '苏州',
      region: '华东',
      deviceType: 'dns',
      action: 'alert',
    },
    {
      severity: 'info',
      category: 'authentication',
      source: '10.0.0.10',
      sourceIp: '10.0.0.10',
      message: '管理员登录成功 - 堡垒机会话开始',
      rawLog: 'Session Start: Admin user "ops_admin" started session from 10.0.0.10 at 2024-01-12 10:00:00',
      rawData: 'Session Start: Admin user "ops_admin" started session from 10.0.0.10 at 2024-01-12 10:00:00',
      tags: ['admin', 'session', 'audit'],
      threatName: '管理员会话记录',
      threatLevel: 'info',
      sourceChannel: '堡垒机',
      country: '中国',
      city: '郑州',
      region: '华中',
      userName: 'ops_admin',
      deviceType: 'bastion',
      action: 'log',
    },
  ];

  for (const event of sampleEvents) {
    await prisma.securityEvent.create({ data: event });
  }

  console.log('Created sample security events');

  // Create sample alert forwarding rules
  const alertRules = [
    {
      name: '严重告警转发 Webhook',
      description: '将所有严重和高危安全事件转发到Webhook',
      enabled: true,
      type: 'webhook',
      destination: 'https://webhook.site/your-webhook-id',
      conditions: {
        severity: ['critical', 'high'],
      },
    },
    {
      name: '邮件通知 - 入侵检测',
      description: '当检测到入侵事件时发送邮件通知',
      enabled: true,
      type: 'email',
      destination: 'security-team@example.com',
      conditions: {
        category: ['intrusion', 'malware'],
        severity: ['critical', 'high', 'medium'],
      },
    },
    {
      name: 'Syslog转发 - 全部事件',
      description: '将所有安全事件转发到SIEM系统',
      enabled: false,
      type: 'syslog',
      destination: 'siem.example.com:514',
      conditions: {
        severity: ['critical', 'high', 'medium', 'low', 'info'],
      },
    },
    {
      name: '钉钉告警通知',
      description: '通过钉钉机器人推送高危告警',
      enabled: true,
      type: 'webhook',
      destination: 'https://oapi.dingtalk.com/robot/send?access_token=xxx',
      conditions: {
        severity: ['critical'],
      },
    },
    {
      name: '企业微信告警',
      description: '通过企业微信推送安全事件',
      enabled: false,
      type: 'webhook',
      destination: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx',
      conditions: {
        severity: ['critical', 'high'],
        category: ['intrusion'],
      },
    },
  ];

  for (const ruleData of alertRules) {
    await prisma.alertForwardingRule.upsert({
      where: {
        id: `seed-${ruleData.name.replace(/\s+/g, '-').toLowerCase()}`,
      },
      update: {},
      create: {
        ...ruleData,
      },
    });
  }

  console.log('Created sample alert forwarding rules');

  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
